version: '3.8'

services:
  diem-ecommerce-master-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: diem-ecommerce-master-sqlserver
    restart: unless-stopped
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"  # Enable SQL Server Agent for replication
    ports:
      - "1433:1433"
    networks:
      - diem-ecommerce-network
    volumes:
      - diem-ecommerce-master-data:/var/opt/mssql
    user: root
  
  diem-ecommerce-slave-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: diem-ecommerce-slave-sqlserver
    restart: unless-stopped
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"  # Enable SQL Server Agent for replication
    ports:
      - "1434:1433"
    networks:
      - diem-ecommerce-network
    volumes:
      - diem-ecommerce-slave-data:/var/opt/mssql
    user: root

  diem-ecommerce-redis:
    image: redis:alpine
    container_name: diem-ecommerce-redis
    restart: unless-stopped
    command: redis-server --requirepass ${DB_PASSWORD} --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - diem-ecommerce-network
    volumes:
      - diem-ecommerce-redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M

  diem-ecommerce-api:
    build:
      context: .
      dockerfile: DiemEcommerce.API/Dockerfile
    container_name: diem-ecommerce-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__MasterConnection: Server=diem-ecommerce-master-sqlserver;Database=DiemEcommerceMaster;User=sa;Password=${DB_PASSWORD};Trust Server Certificate=True;
      ConnectionStrings__SlaveConnection: Server=diem-ecommerce-slave-sqlserver;Database=DiemEcommerceSlave;User=sa;Password=${DB_PASSWORD};Trust Server Certificate=True;
      ConnectionStrings__Redis: diem-ecommerce-redis:6379,password=${DB_PASSWORD}
      Logging__LogLevel__Default: Error
      Logging__LogLevel__Microsoft: Error
      Logging__LogLevel__Microsoft.AspNetCore: Error
      JwtOptions__SecretKey: ${JWT_SECRET}
      JwtOptions__Issuer: ${JWT_ISSUER}
      JwtOptions__Audience: ${JWT_AUDIENCE}
      JwtOptions__ExpireMinutes: 28800
      MailOption__Mail: ${MAIL}
      MailOption__Password: ${MAIL_PASSWORD}
      MailOption__Host: ${MAIL_HOST}
      MailOption__Port: ${MAIL_PORT}
      MailOption__DisplayName: ${MAIL_DISPLAY_NAME}
      CloudinaryOptions__CloudName: ${CLOUDINARY_CLOUD_NAME}
      CloudinaryOptions__ApiKey: ${CLOUDINARY_API_KEY}
      CloudinaryOptions__ApiSecret: ${CLOUDINARY_API_SECRET}
      SqlServerRetryOptions__MaxRetryCount: 5
      SqlServerRetryOptions__MaxRetryDelay: "00:00:05"
      SqlServerRetryOptions__ErrorNumbersToAdd: [ ]
      AllowedHosts: "*"
    networks:
      - diem-ecommerce-network
    depends_on:
      - diem-ecommerce-master-sqlserver
      - diem-ecommerce-slave-sqlserver
      - diem-ecommerce-redis

volumes:
  diem-ecommerce-master-data:
    name: diem-ecommerce-master-data
    driver: local
  diem-ecommerce-slave-data:
    name: diem-ecommerce-slave-data
    driver: local
  diem-ecommerce-redis-data:
    name: diem-ecommerce-redis-data
    driver: local

networks:
  diem-ecommerce-network:
    name: diem-ecommerce-network
    driver: bridge
    ipam:
      driver: default